# PRODUCTION DOCKER COMPOSE FILE
# ⚠️ WARNING: DO NOT ADD VOLUME MOUNTS TO THIS FILE!
# Volume mounts will override the production build and cause the app to fail.
# This file is specifically for production deployments.
#
# Usage: docker-compose -f docker-compose.prod.yml up -d

services:
  protokol57:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: https://bazptglwzqstppwlvmvb.supabase.co
        VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhenB0Z2x3enFzdHBwd2x2bXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTc1OTAsImV4cCI6MjA2NDU5MzU5MH0.xRh0LCDWP6YD3F4mDGrIK3krwwZw-DRx0iXy7MmIPY8
        VITE_TELEGRAM_BOT_USERNAME: protokol57bot
    ports:
      - "5001:5000"
    # ⚠️ NO VOLUME MOUNTS! They break production by overriding built assets
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MAILTRAP_API_TOKEN=${MAILTRAP_API_TOKEN}
      - MAILTRAP_SMTP_HOST=${MAILTRAP_SMTP_HOST}
      - MAILTRAP_SMTP_PORT=${MAILTRAP_SMTP_PORT}
      - MAILTRAP_SMTP_USERNAME=${MAILTRAP_SMTP_USERNAME}
      - MAILTRAP_SMTP_PASSWORD=${MAILTRAP_SMTP_PASSWORD}
    restart: unless-stopped
    stdin_open: false
    tty: false
    networks:
      - protokol-network
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    user: "node"
    read_only: false
    # Traefik labels for production routing
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.protokol57-main.rule=Host(`p57.birfoiz.uz`) || Host(`srv852801.hstgr.cloud`)"
      - "traefik.http.routers.protokol57-main.entrypoints=web,websecure"
      - "traefik.http.routers.protokol57-main.tls=true"
      - "traefik.http.routers.protokol57-main.tls.certresolver=mytlschallenge"
      - "traefik.http.services.protokol57-main.loadbalancer.server.port=5000"

networks:
  protokol-network:
    driver: bridge
  default:
    external:
      name: root_default