version: "3.7"

services:
  traefik:
    image: "traefik"
    restart: always
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=hurshidbey@gmail.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  protokol57-proxy:
    image: nginx:alpine
    restart: always
    command: >
      sh -c "echo 'server {
        listen 80;
        location / {
          proxy_pass http://172.17.0.1:5000;
          proxy_set_header Host \$$host;
          proxy_set_header X-Real-IP \$$remote_addr;
          proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto \$$scheme;
        }
      }' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.protokol57.rule=Host(`p57.birfoiz.uz`) || Host(`srv852801.hstgr.cloud`)"
      - "traefik.http.routers.protokol57.entrypoints=web,websecure"
      - "traefik.http.routers.protokol57.tls=true"
      - "traefik.http.routers.protokol57.tls.certresolver=mytlschallenge"

volumes:
  traefik_data:
    external: true