services:
  protokol57:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=5000
      # Supabase connection - using fallback to in-memory storage if not set
      - SUPABASE_URL=${SUPABASE_URL:-}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD:-}
      - DATABASE_URL=${DATABASE_URL:-}
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - protokol-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/protocols"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  protokol-network:
    driver: bridge