services:
  protokol57:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_TELEGRAM_BOT_USERNAME: ${VITE_TELEGRAM_BOT_USERNAME:-protokol57bot}
    ports:
      - "5001:5000"
    # Volume mounts removed to prevent overriding built assets in production
    env_file:
      - .env.production
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MAILTRAP_API_TOKEN=${MAILTRAP_API_TOKEN}
      - MAILTRAP_SMTP_HOST=${MAILTRAP_SMTP_HOST}
      - MAILTRAP_SMTP_PORT=${MAILTRAP_SMTP_PORT}
      - MAILTRAP_SMTP_USERNAME=${MAILTRAP_SMTP_USERNAME}
      - MAILTRAP_SMTP_PASSWORD=${MAILTRAP_SMTP_PASSWORD}
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - protokol-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s

networks:
  protokol-network:
    driver: bridge
