# PRODUCTION DOCKER COMPOSE FILE
# ⚠️ WARNING: DO NOT ADD VOLUME MOUNTS TO THIS FILE!
# Volume mounts will override the production build and cause the app to fail.
# This file is specifically for production deployments.
#
# Usage: docker-compose -f docker-compose.prod.yml up -d

services:
  protokol57:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_TELEGRAM_BOT_USERNAME: ${VITE_TELEGRAM_BOT_USERNAME:-protokol57bot}
    ports:
      - "5001:5000"
    # ⚠️ NO VOLUME MOUNTS! They break production by overriding built assets
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MAILTRAP_API_TOKEN=${MAILTRAP_API_TOKEN}
      - MAILTRAP_SMTP_HOST=${MAILTRAP_SMTP_HOST}
      - MAILTRAP_SMTP_PORT=${MAILTRAP_SMTP_PORT}
      - MAILTRAP_SMTP_USERNAME=${MAILTRAP_SMTP_USERNAME}
      - MAILTRAP_SMTP_PASSWORD=${MAILTRAP_SMTP_PASSWORD}
    restart: unless-stopped
    stdin_open: false
    tty: false
    networks:
      - protokol-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  protokol-network:
    driver: bridge