version: "3.7"

services:
  traefik:
    image: "traefik"
    restart: always
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=hurshidbey@gmail.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.protokol57.rule=Host(`p57.birfoiz.uz`) || Host(`srv852801.hstgr.cloud`)"
      - "traefik.http.routers.protokol57.entrypoints=web,websecure"
      - "traefik.http.routers.protokol57.tls=true"
      - "traefik.http.routers.protokol57.tls.certresolver=mytlschallenge"
      - "traefik.http.services.protokol57.loadbalancer.server.url=http://172.17.0.1:5000"

volumes:
  traefik_data:
    external: true