services:
  protokol57:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: https://bazptglwzqstppwlvmvb.supabase.co
        VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhenB0Z2x3enFzdHBwd2x2bXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTc1OTAsImV4cCI6MjA2NDU5MzU5MH0.xRh0LCDWP6YD3F4mDGrIK3krwwZw-DRx0iXy7MmIPY8
        VITE_TELEGRAM_BOT_USERNAME: protokol57bot
    ports:
      - "5001:5000"
    # Remove volume mounts in production to prevent overriding built assets
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.production
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MAILTRAP_API_TOKEN=${MAILTRAP_API_TOKEN}
      - MAILTRAP_SMTP_HOST=${MAILTRAP_SMTP_HOST}
      - MAILTRAP_SMTP_PORT=${MAILTRAP_SMTP_PORT}
      - MAILTRAP_SMTP_USERNAME=${MAILTRAP_SMTP_USERNAME}
      - MAILTRAP_SMTP_PASSWORD=${MAILTRAP_SMTP_PASSWORD}
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - protokol-network
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.protokol57-main.rule=Host(`p57.birfoiz.uz`) || Host(`srv852801.hstgr.cloud`)"
      - "traefik.http.routers.protokol57-main.entrypoints=web,websecure"
      - "traefik.http.routers.protokol57-main.tls=true"
      - "traefik.http.routers.protokol57-main.tls.certresolver=mytlschallenge"
      - "traefik.http.services.protokol57-main.loadbalancer.server.port=5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 40s

networks:
  protokol-network:
    driver: bridge
  default:
    external:
      name: root_default
