services:
  protokol57:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: https://bazptglwzqstppwlvmvb.supabase.co
        VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhenB0Z2x3enFzdHBwd2x2bXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTc1OTAsImV4cCI6MjA2NDU5MzU5MH0.xRh0LCDWP6YD3F4mDGrIK3krwwZw-DRx0iXy7MmIPY8
        VITE_TELEGRAM_BOT_USERNAME: protokol57bot
    ports:
      - "5001:5000"
    volumes:
      # Development volume mounts for hot reload
      - .:/app
      - /app/node_modules
    env_file:
      - .env.production
    environment:
      - NODE_ENV=development
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - protokol-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/protocols"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 40s

networks:
  protokol-network:
    driver: bridge